#!/usr/bin/env python3

import pygame
import random

class Ball:
    def __init__(self, pos, size):
        (self.x, self.y) = pos
        self.size = size
        self.colour = (255,209,220)
        self.thickness = 0

    def display(self, screen):
        pygame.draw.circle(screen, self.colour, (self.x, self.y), self.size, self.thickness)

def main():
    # config options
    (width, height) = (1750, 1200);
    bg_color = (125,125,125)
    ball_color = (255,209,220)
    num_balls = 10

    # set up the screen
    screen = pygame.display.set_mode((width, height))
    pygame.display.set_caption("BaBounce")
    screen.fill(bg_color)

    # generate random balls
    balls = []
    for n in range(num_balls):
        size = random.randint(25,100)
        x = random.randint(size, width-size)
        y = random.randint(size, height-size)
        balls.append(Ball((x,y), size))

    # display the balls
    for ball in balls:
        ball.display(screen)

    # show everything
    pygame.display.flip()

    # run the program
    running = True
    while running:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False


if __name__ == "__main__":
    main()
